### ISSUE TITLE
bug help pls

### ISSUE THREAD

**Issue by aminepro1** [Alexell/BlumBot#13]
Traceback (most recent call last):
  File "D:\BOTS\BlumBot-main\bot\core\bot.py", line 124, in daily_reward
    log.warning(f"{self.session_name} | Unknown response in daily reward: {response_text}")
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_logger.py", line 2052, in warning
    __self._log("WARNING", False, __self._options, __message, args, kwargs)
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<![endif]-->" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BOTS\BlumBot-main\bot\core\bot.py", line 362, in run
    daily_claimed = await self.daily_reward()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BOTS\BlumBot-main\bot\core\bot.py", line 131, in daily_reward
    log.error(f"{self.session_name} | Daily reward error: {str(error)}")
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<![endif]-->" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BOTS\BlumBot-main\main.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\BOTS\BlumBot-main\main.py", line 6, in main
    await launcher.start()
  File "D:\BOTS\BlumBot-main\bot\core\launcher.py", line 108, in start
    await run_clients(tg_clients=tg_clients)
  File "D:\BOTS\BlumBot-main\bot\core\launcher.py", line 84, in run_clients
    await asyncio.gather(*tasks)
  File "D:\BOTS\BlumBot-main\bot\core\launcher.py", line 71, in run_bot_with_delay
    await run_bot(tg_client=tg_client, proxy=proxy)
  File "D:\BOTS\BlumBot-main\bot\core\bot.py", line 429, in run_bot
    await CryptoBot(tg_client=tg_client).run(proxy=proxy)
  File "D:\BOTS\BlumBot-main\bot\core\bot.py", line 421, in run
    log.error(f"{self.session_name} | Unknown error: {error}")
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "D:\BOTS\BlumBot-main\venv\Lib\site-packages\loguru\_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<![endif]-->" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
Для продолжения нажмите любую клавишу . . .

**Comment by ivan52605** [comment]
Юзай Пайтон 3.11 и поставь бота с 0
